import type { Locale } from "@/i18n/config";
import { deepTypo } from "@/lib/typograph";

/** Copy for the home page sections, both languages side by side. */

const uk = {
  hero: {
    overline: "Стоматологія у Львові · з 2014 року",
    chips: ["Рейтинг 4,9 у Google", "12 років досвіду", "Гарантія до 5 років", "Лікування без болю"],
    floatingDoctor: { name: "Андрій Соловій", role: "Головний лікар · 2 600+ імплантів" },
    floatingPlan: { title: "3D-план за 1 візит", text: "Ціну фіксуємо до початку" },
    mediaAlt: "Пацієнтка сміється разом із лікарем у світлому кабінеті NaDent",
  },
  trust: {
    rating: "612 відгуків у Google",
    license: "Ліцензія МОЗ України",
    patients: "пацієнтів довірилися нам",
    brandsLabel: "Працюємо з перевіреними брендами",
  },
  problems: {
    overline: "Почнімо з головного",
    title: "З чим ви до нас прийшли?",
    lead: "Оберіть, що турбує, — покажемо рішення, ціну і терміни.",
  },
  services: {
    overline: "Послуги",
    title: "Усе для здорової усмішки. В одній клініці.",
    lead: "Від профілактики до повного відновлення зубів — з прозорою ціною на кожному етапі.",
  },
  why: {
    overline: "Чому NaDent",
    title: "Не обіцяємо. Показуємо цифрами.",
    items: [
      { value: 12, suffix: "", unit: "років", text: "лікуємо у Львові. Команда з 9 лікарів, кожен — у своїй спеціалізації." },
      { value: 4200, suffix: "+", unit: "імплантів", text: "встановлено. 98 % приживлення за даними нашого контролю." },
      { value: 3, suffix: "D", unit: "план", text: "лікування до його початку. Ви бачите результат і знаєте ціну." },
      { value: 1, suffix: "", unit: "день", text: "на коронку чи вкладку завдяки власному фрезерному центру CEREC." },
      { value: 0, suffix: "", unit: "грн", text: "прихованих доплат. Вартість фіксуємо в письмовому плані." },
      { value: 15, suffix: "", unit: "хв", text: "і ми відповімо на заявку в робочий час. У неділю працює черговий лікар." },
    ],
  },
  tech: {
    overline: "Технології",
    title: "Обладнання, яке працює на ваш комфорт.",
    lead: "Кожен пристрій тут для того, щоб лікування було точнішим, швидшим і спокійнішим.",
    more: "Усі технології",
  },
  cases: {
    overline: "До / після",
    title: "Результати, які говорять самі за себе.",
    lead: "Перетягніть повзунок, щоб порівняти. Кожен кейс — реальна історія пацієнта.",
    all: "Усі",
    task: "Задача",
    solution: "Рішення",
    result: "Результат",
    duration: "Термін",
    visits: "Візити",
    doctor: "Лікар",
    slider: "Порівняння фото до і після лікування",
    before: "До",
    after: "Після",
  },
  doctors: {
    overline: "Команда",
    title: "Лікарі, яким довіряють найскладніше.",
    lead: "Кожен лікар працює у своїй спеціалізації й щороку навчається в Європі.",
  },
  fear: {
    overline: "Для тих, кому страшно",
    title: "Боїтеся стоматолога? Це нормально.",
    lead: "Страх — одна з найчастіших причин відкладати лікування. Ми побудували клініку так, щоб вам було спокійно — від першого дзвінка до останнього візиту.",
    points: [
      { title: "Анестезія, яку не відчуваєте", text: "Комп'ютерна система вводить анестетик повільно, тож укол майже непомітний." },
      { title: "Лікування уві сні", text: "Медикаментозна седація під наглядом анестезіолога: заснули — прокинулись з вилікуваними зубами." },
      { title: "Жодного осуду", text: "Скільки б часу не минуло від останнього візиту, ми просто допоможемо." },
      { title: "Ви керуєте процесом", text: "Підняли руку — ми зупинились. Пояснюємо кожен крок до того, як його зробити." },
    ],
    cta: "Дізнатися про лікування уві сні",
    ctaAlt: "Прийти просто поговорити",
    mediaAlt: "Спокійна пацієнтка в навушниках і під пледом у стоматологічному кріслі",
  },
  firstVisit: {
    overline: "Перший візит",
    title: "Що буде, коли ви прийдете.",
    lead: "Жодних несподіванок: ви знаєте кожен крок заздалегідь.",
    steps: [
      { title: "Знайомство і розмова", meta: "5–10 хв", text: "Кава чи вода, коротка анкета. Лікар розпитує, що турбує і чого ви очікуєте." },
      { title: "Огляд і 3D-діагностика", meta: "15 хв", text: "Огляд, 3D-сканування зубів і за потреби КТ. Показуємо все на екрані." },
      { title: "План лікування з варіантами", meta: "10–15 хв", text: "2–3 варіанти: від необхідного мінімуму до ідеального результату, з цінами й термінами." },
      { title: "Відповіді на всі питання", meta: "скільки потрібно", text: "Ви вирішуєте, коли й з чого почати. Ніякого тиску." },
      { title: "План у вашому телефоні", meta: "у день візиту", text: "Надсилаємо письмовий план у месенджер. Вартість зафіксована." },
    ],
    note: "Консультація — 500 грн, враховується у вартість лікування.",
    cta: "Детальніше про перший візит",
  },
  prices: {
    overline: "Ціни",
    title: "Прозоро до гривні.",
    lead: "Ціни «від» для найпопулярніших послуг. Точну вартість лікар фіксує в плані після діагностики.",
    calcTitle: "Розстрочка 0 %",
    calcLead: "Розрахуйте щомісячний платіж. Оформлення за 2 хвилини, без переплат.",
    amount: "Сума лікування",
    months: "Кількість місяців",
    monthly: "Щомісячний платіж",
    partners: "через monobank та ПриватБанк",
    monthsShort: "міс",
  },
  quiz: {
    overline: "Калькулятор",
    title: "Дізнайтеся вартість лікування за 1 хвилину.",
    lead: "5 простих питань — і ви отримаєте орієнтовний діапазон ціни та рекомендацію, з чого почати.",
    cta: "Почати",
    meta: ["5 питань", "≈ 1 хвилина", "без реєстрації"],
  },
  reviews: {
    overline: "Відгуки",
    title: "Що кажуть наші пацієнти.",
    videoTitle: "Відео-відгук",
    videoSoon: "Реальні відео — незабаром",
    ratingLabel: "Середня оцінка",
    of: "з 5",
  },
  guarantees: {
    overline: "Гарантії",
    title: "Відповідаємо за результат. Письмово.",
    items: [
      { title: "Імпланти", value: "Довічно", text: "Гарантія виробника Straumann та Nobel Biocare. Не прижився — замінимо безкоштовно." },
      { title: "Коронки, вініри, протези", value: "5 років", text: "Відкололось чи розхиталось із нашої вини — переробимо за наш рахунок." },
      { title: "Пломби і канали", value: "3 роки", text: "На реставрації та лікування каналів під мікроскопом." },
      { title: "Умова одна", value: "2 рази на рік", text: "Професійна гігієна кожні 6 місяців: так ми разом стежимо за результатом." },
    ],
    note: "Усі умови прописані в договорі, який ви отримуєте до початку лікування.",
  },
  sterile: {
    overline: "Безпека",
    title: "Стерильність, яку можна перевірити.",
    lead: "Інструменти проходять п'ять етапів обробки, а стерильний пакет ми відкриваємо при вас.",
    steps: ["Дезінфекція одразу після використання", "Ультразвукове очищення", "Пакування в крафт-пакети з індикатором", "Стерилізація в автоклаві класу B", "Зберігання в закритих шафах до відкриття при вас"],
    mediaAlt: "Стерилізаційна кімната з автоклавом і запакованими інструментами",
  },
  faq: {
    overline: "Питання",
    title: "Часті питання.",
    more: "Усі питання і відповіді",
  },
  finalCta: {
    title: "Перший крок — найпростіший.",
    lead: "Залиште номер: адміністратор передзвонить протягом 15 хвилин, підбере зручний час і відповість на питання.",
    mediaAlt: "Рецепція клініки NaDent",
  },
  contacts: {
    overline: "Контакти",
    title: "Легко дістатися.",
    address: "Адреса",
    hours: "Графік",
    phone: "Телефон",
    parking: "Паркування",
    parkingText: "Велика безкоштовна парковка біля будівлі.",
    transport: "Громадський транспорт",
    transportText: "Зупинка «вул. Кульпарківська» — 3 хвилини пішки.",
    shelter: "Укриття",
    shelterText: "Найближче укриття — у сусідній будівлі, 2 хвилини пішки.",
    today: "сьогодні",
  },
};

type HomeCopy = typeof uk;

const en: HomeCopy = {
  hero: {
    overline: "Dental clinic in Lviv · since 2014",
    chips: ["Rated 4.9 on Google", "12 years of experience", "Up to 5-year guarantee", "Pain-free treatment"],
    floatingDoctor: { name: "Dr Andrii Solovii", role: "Medical director · 2,600+ implants" },
    floatingPlan: { title: "3D plan in one visit", text: "Price fixed before we start" },
    mediaAlt: "A patient laughing with her dentist in a bright NaDent treatment room",
  },
  trust: {
    rating: "612 Google reviews",
    license: "Licensed by Ukraine's Ministry of Health",
    patients: "patients have trusted us",
    brandsLabel: "We work with proven brands",
  },
  problems: {
    overline: "Let's start with what matters",
    title: "What brings you in?",
    lead: "Choose what's bothering you — we'll show the solution, price and timeline.",
  },
  services: {
    overline: "Services",
    title: "Everything for a healthy smile. Under one roof.",
    lead: "From prevention to full-mouth restoration — with a transparent price at every step.",
  },
  why: {
    overline: "Why NaDent",
    title: "No promises. Just numbers.",
    items: [
      { value: 12, suffix: "", unit: "years", text: "of treating patients in Lviv. A team of 9 doctors, each in their own specialty." },
      { value: 4200, suffix: "+", unit: "implants", text: "placed, with a 98% success rate in our own follow-up." },
      { value: 3, suffix: "D", unit: "plan", text: "of your treatment before it starts. You see the result and know the price." },
      { value: 1, suffix: "", unit: "day", text: "for a crown or inlay, thanks to our in-house CEREC milling centre." },
      { value: 0, suffix: "", unit: "UAH", text: "in hidden extras. The price is fixed in your written plan." },
      { value: 15, suffix: "", unit: "min", text: "to reply to your request during opening hours. A duty dentist works on Sundays." },
    ],
  },
  tech: {
    overline: "Technology",
    title: "Equipment that works for your comfort.",
    lead: "Every device is here to make treatment more precise, faster and calmer.",
    more: "All technology",
  },
  cases: {
    overline: "Before / after",
    title: "Results that speak for themselves.",
    lead: "Drag the slider to compare. Every case is a real patient's story.",
    all: "All",
    task: "Challenge",
    solution: "Solution",
    result: "Result",
    duration: "Duration",
    visits: "Visits",
    doctor: "Doctor",
    slider: "Before and after treatment comparison",
    before: "Before",
    after: "After",
  },
  doctors: {
    overline: "Team",
    title: "Doctors trusted with the hardest cases.",
    lead: "Every doctor works in their own specialty and trains in Europe every year.",
  },
  fear: {
    overline: "For anxious patients",
    title: "Scared of the dentist? That's normal.",
    lead: "Fear is one of the most common reasons people put off treatment. We built the clinic so you feel calm — from the first call to the last visit.",
    points: [
      { title: "Anaesthesia you don't feel", text: "A computer-controlled system delivers anaesthetic slowly, so the injection is barely noticeable." },
      { title: "Treatment while you sleep", text: "Conscious sedation supervised by an anaesthesiologist: fall asleep, wake up with the work done." },
      { title: "No judgement", text: "However long it's been since your last visit, we're simply here to help." },
      { title: "You're in control", text: "Raise your hand and we stop. We explain every step before we take it." },
    ],
    cta: "About sedation dentistry",
    ctaAlt: "Come in just to talk",
    mediaAlt: "A calm patient with headphones and a blanket in a dental chair",
  },
  firstVisit: {
    overline: "First visit",
    title: "What happens when you arrive.",
    lead: "No surprises: you know every step in advance.",
    steps: [
      { title: "Welcome and a chat", meta: "5–10 min", text: "Coffee or water and a short form. The doctor asks what's bothering you and what you hope for." },
      { title: "Examination and 3D diagnostics", meta: "15 min", text: "Examination, a 3D scan and a CBCT if needed. We show you everything on screen." },
      { title: "A plan with options", meta: "10–15 min", text: "2–3 options, from the essential minimum to the ideal result, with prices and timelines." },
      { title: "All your questions answered", meta: "as long as you need", text: "You decide when and where to start. No pressure." },
      { title: "The plan on your phone", meta: "same day", text: "We send the written plan to your messenger. The price is fixed." },
    ],
    note: "The consultation costs UAH 500 and is credited towards treatment.",
    cta: "More about the first visit",
  },
  prices: {
    overline: "Prices",
    title: "Transparent to the last hryvnia.",
    lead: "“From” prices for our most popular treatments. Your doctor fixes the exact price in your plan after diagnostics.",
    calcTitle: "0% instalments",
    calcLead: "Work out your monthly payment. Arranged in two minutes, no extra cost.",
    amount: "Treatment cost",
    months: "Number of months",
    monthly: "Monthly payment",
    partners: "via monobank and PrivatBank",
    monthsShort: "mo",
  },
  quiz: {
    overline: "Cost estimator",
    title: "Find out what treatment costs in one minute.",
    lead: "Five simple questions — and you'll get an estimated price range and a recommendation on where to start.",
    cta: "Start",
    meta: ["5 questions", "≈ 1 minute", "no sign-up"],
  },
  reviews: {
    overline: "Reviews",
    title: "What our patients say.",
    videoTitle: "Video review",
    videoSoon: "Real videos coming soon",
    ratingLabel: "Average rating",
    of: "out of 5",
  },
  guarantees: {
    overline: "Guarantees",
    title: "We stand behind the result. In writing.",
    items: [
      { title: "Implants", value: "Lifetime", text: "Straumann and Nobel Biocare manufacturer's guarantee. If it fails, we replace it free." },
      { title: "Crowns, veneers, prostheses", value: "5 years", text: "If it chips or loosens through our fault, we redo it at our cost." },
      { title: "Fillings & root canals", value: "3 years", text: "On restorations and microscope root canal treatment." },
      { title: "One condition", value: "Twice a year", text: "A professional clean every six months, so we look after the result together." },
    ],
    note: "All terms are set out in the contract you receive before treatment starts.",
  },
  sterile: {
    overline: "Safety",
    title: "Sterility you can verify.",
    lead: "Instruments go through five processing stages, and the sterile pouch is opened in front of you.",
    steps: ["Disinfection right after use", "Ultrasonic cleaning", "Sealed pouches with indicators", "Sterilisation in a class B autoclave", "Stored in closed cabinets until opened in front of you"],
    mediaAlt: "Sterilisation room with an autoclave and sealed instrument pouches",
  },
  faq: {
    overline: "Questions",
    title: "Frequently asked questions.",
    more: "All questions and answers",
  },
  finalCta: {
    title: "The first step is the easiest.",
    lead: "Leave your number: our coordinator will call back within 15 minutes, find a convenient time and answer your questions.",
    mediaAlt: "NaDent clinic reception",
  },
  contacts: {
    overline: "Contacts",
    title: "Easy to reach.",
    address: "Address",
    hours: "Opening hours",
    phone: "Phone",
    parking: "Parking",
    parkingText: "A large free car park next to the building.",
    transport: "Public transport",
    transportText: "“Kulparkivska St” stop — a 3-minute walk.",
    shelter: "Shelter",
    shelterText: "The nearest shelter is in the neighbouring building, a 2-minute walk.",
    today: "today",
  },
};

export function getHomeCopy(locale: Locale): HomeCopy {
  return deepTypo(locale === "uk" ? uk : en, locale);
}

export const brandWordmarks = ["Straumann", "Nobel Biocare", "Osstem", "Carl Zeiss", "3Shape", "Planmeca", "Dentsply Sirona", "Ivoclar", "EMS", "Philips Zoom"];
