/**
 * Every image slot on the site. Single source of truth for:
 *  - ImageSlot ids (typed), default aspect ratio and placeholder icon;
 *  - docs/IMAGE_PROMPTS.md (generated by scripts/image-prompts.ts).
 *
 * To add a real photo: save it as public/images/<id>.jpg (or .png/.webp) and rebuild.
 * Keep this file free of path-alias imports: it is also executed directly by Node.
 */

export type ImageKind = "hero" | "interior" | "equipment" | "portrait" | "people" | "service" | "case" | "video" | "og";

export interface ImageSpec {
  kind: ImageKind;
  /** "w:h" */
  aspect: string;
  /** Minimum source resolution */
  min: string;
  /** Where it is used */
  usedOn: string;
  /** What must be in the frame */
  subject: string;
  /** Mood and light */
  mood?: string;
  /** Ready-to-use English prompt; the shared style suffix is appended in the doc */
  prompt: string;
  /** Extra negative prompt on top of the shared one */
  negative?: string;
  /** Real photo only (no AI): before/after, real reviews */
  realOnly?: boolean;
}

const MOOD_CLINIC = "Soft diffused daylight from large windows, calm, warm-neutral palette (ivory, sand, soft teal accents)";
const MOOD_PORTRAIT = "Soft key light at 45°, gentle fill, warm-neutral seamless backdrop (#EFEAE3), shallow depth of field";

const services = {
  implants: {
    subject: "Close, reassuring moment: implantologist showing a 3D model of a dental implant to a man in his late 50s",
    prompt:
      "A calm dental implant consultation in a bright minimalist clinic, a male implantologist in a navy scrub top holds a precise titanium implant model and explains it to a smiling grey-haired man in his late fifties sitting in a modern cream dental chair, large monitor in soft focus showing a 3D jaw scan",
  },
  "all-on-4": {
    subject: "Confident senior woman laughing naturally at a dinner table, full natural-looking smile",
    prompt:
      "A confident woman in her mid sixties laughing naturally while eating an apple at a sunlit kitchen table, natural-looking healthy teeth, relaxed and joyful, lifestyle photography, shallow depth of field",
  },
  veneers: {
    subject: "Young woman looking at her smile in a hand mirror after treatment, natural shade teeth",
    prompt:
      "A woman around thirty looking at her new smile in a round hand mirror while sitting in a bright minimalist dental studio, natural-shade veneers (not overly white), genuine delighted expression, dentist's gloved hand partially visible",
  },
  aligners: {
    subject: "Hand holding a clear aligner near a smiling face; aligner clearly visible and transparent",
    prompt:
      "Macro-leaning lifestyle shot of a woman's hand holding a transparent clear aligner in front of her softly smiling face, crystal clear plastic catching light, minimalist bright background",
  },
  braces: {
    subject: "Teenager with modern ceramic braces smiling confidently",
    prompt:
      "A cheerful teenage boy around fifteen with discreet tooth-coloured ceramic braces smiling at the camera in a bright orthodontic clinic, natural pose, soft background",
  },
  whitening: {
    subject: "Woman relaxing during in-office whitening, calm atmosphere, no harsh blue light",
    prompt:
      "A relaxed woman reclining in a modern dental chair during professional teeth whitening, eyes closed, wearing soft protective glasses, calm spa-like atmosphere, subtle cool light, hygienist in the background",
  },
  hygiene: {
    subject: "Hygienist performing professional cleaning, calm patient, clean instruments",
    prompt:
      "A dental hygienist in light scrubs performing a gentle professional teeth cleaning on a calm patient, ultrasonic scaler, protective eyewear, bright clean treatment room, focus on care and precision",
  },
  caries: {
    subject: "Dentist working with magnification loupes, precise composite restoration",
    prompt:
      "A female dentist wearing magnification loupes carefully restoring a tooth with composite, assistant beside her, overhead dental light, calm focused atmosphere, patient comfortable with blanket",
  },
  endodontics: {
    subject: "Endodontist working at a surgical dental microscope",
    prompt:
      "An endodontist looking through a large white dental operating microscope during a root canal procedure, assistant beside, clean ergonomic setup, precise and high-tech atmosphere",
  },
  prosthetics: {
    subject: "Zirconia crown on a fingertip / in a dental technician's hand, milled crowns on a tray",
    prompt:
      "A dental technician's hand holding a finished natural-looking zirconia crown with tweezers, several milled crowns on a white tray, CAD/CAM milling unit softly blurred behind",
  },
  surgery: {
    subject: "Calm surgical suite, sterile setup, surgeon preparing (no blood)",
    prompt:
      "A pristine dental surgical suite with sterile blue drapes and neatly arranged instruments, surgeon in cap and mask adjusting the operating light, calm and controlled, no blood",
  },
  kids: {
    subject: "Kind female dentist and a 6-year-old girl giving a high five in the chair",
    prompt:
      "A kind female pediatric dentist giving a high five to a smiling six-year-old girl sitting in a colourful but tasteful kids' dental chair, playful soft decor, parent smiling in the background",
  },
  sedation: {
    subject: "Patient calmly asleep under sedation with anesthesiologist monitoring vitals",
    prompt:
      "A patient peacefully resting under light sedation in a modern dental chair with a soft blanket, anesthesiologist in scrubs checking a vitals monitor, dim warm light, sense of safety and calm",
  },
  emergency: {
    subject: "Evening clinic, doctor welcoming a patient holding his cheek, warm lights",
    prompt:
      "Evening at a modern dental clinic reception, warm lights on, a friendly dentist welcoming a young man who holds his cheek in discomfort, reassuring gesture, city lights through the window",
  },
} as const;

const tech = {
  ct: ["CBCT scanner (3D X-ray)", "A modern cone beam CT dental scanner in a bright room, patient positioned calmly, radiologic technician adjusting settings, sleek white equipment"],
  scanner: ["Intraoral 3D scanner and live 3D model on screen", "A dentist holding a slim intraoral 3D scanner near a patient while a large screen shows a colourful live 3D model of the teeth"],
  microscope: ["Dental operating microscope close-up", "Close-up of a white dental operating microscope with illuminated optics, precise engineering details, clean clinic background"],
  cadcam: ["Chairside milling unit producing a crown", "A compact chairside CAD/CAM milling machine with a ceramic block and a freshly milled crown, glass door, soft reflections"],
  laser: ["Dental laser handpiece", "A modern dental diode laser device with a slim handpiece on a clean tray, subtle glow, high-tech minimalism"],
  sedation: ["Sedation monitoring station", "A calm sedation setup: vitals monitor, oxygen equipment and a comfortable chair in soft warm light, clinical but gentle"],
  sterilization: ["Class B autoclave and sealed instrument pouches", "A spotless sterilization room with a class B autoclave, sealed kraft instrument pouches neatly stacked, nurse in gloves labelling a pouch"],
} as const;

const doctors = {
  "andrii-solovii": "a confident male implantologist in his mid forties with short dark hair and a neat beard, navy scrub top",
  "olena-kovalchuk": "a warm elegant female aesthetic dentist around forty with shoulder-length light brown hair, white coat over a beige top",
  "marta-hnatyshyn": "a friendly female orthodontist in her mid thirties with auburn hair in a low bun, soft teal scrub top",
  "taras-boiko": "a calm focused male endodontist around forty with glasses and short hair, charcoal scrub top",
  "iryna-savchuk": "a cheerful female pediatric dentist in her mid thirties with a warm smile and long dark hair, light pink scrub top",
  "ostap-klymko": "an experienced male prosthodontist around fifty with salt-and-pepper hair, white coat",
  "sofiia-dmytruk": "a young female dentist around thirty with a blond ponytail, light teal scrub top",
  "roman-levytskyi": "a reassuring male anesthesiologist in his late forties, clean-shaven, dark green scrub top",
  "yuliia-panchyshyn": "a friendly female dental hygienist in her late twenties with curly dark hair, white scrub top",
} as const;

const cases = {
  "implant-molar": "Missing lower molar replaced with an implant crown",
  "all-on-4-upper": "Full upper arch restored on four implants",
  "veneers-8": "Eight ceramic veneers, natural shade",
  "aligners-crowding": "Crowding corrected with clear aligners",
  "whitening-bright": "In-office whitening, 6 shades lighter",
  "endo-saved-tooth": "Tooth saved with microscope root canal treatment",
} as const;

const articles = {
  "implant-choice": "Close-up of three dental implant models from different systems on a neutral stone surface, precise titanium details",
  "toothache-night": "A bedside table at night with a glass of water and a phone, soft lamp light, sense of late evening (no pills visible)",
  "aligners-vs-braces": "Clear aligners in a case next to a ceramic braces model on a light surface, side-by-side comparison, minimal",
  "veneers-myths": "Porcelain veneer samples arranged on a shade guide on a light table, elegant flat lay",
  "kids-first-visit": "A little boy holding a toothbrush and a plush toy in a bright kids' dental room, playful and calm",
  "sedation-safety": "Calm dental chair with a soft blanket in dim warm light, monitor softly glowing, peaceful atmosphere",
} as const;

function build(): Record<string, ImageSpec> {
  const r: Record<string, ImageSpec> = {
    "hero-desktop": {
      kind: "hero",
      aspect: "16:9",
      min: "2880×1620",
      usedOn: "Головна → Hero (десктоп)",
      subject: "Light, airy treatment room with a patient in her thirties laughing with the doctor; big windows; lots of negative space on the left for floating glass cards",
      mood: MOOD_CLINIC,
      prompt:
        "Wide cinematic shot of a light airy premium dental clinic treatment room with floor-to-ceiling windows, a woman in her thirties sitting upright in a cream leather dental chair laughing naturally with a male dentist in a navy scrub top, minimal Scandinavian interior with oak and travertine, plants, generous negative space on the left third",
    },
    "hero-mobile": {
      kind: "hero",
      aspect: "4:5",
      min: "1440×1800",
      usedOn: "Головна → Hero (мобільний)",
      subject: "Same scene as hero-desktop, vertical crop: patient and doctor centred, window light",
      mood: MOOD_CLINIC,
      prompt:
        "Vertical portrait composition in a light premium dental clinic, a woman in her thirties in a cream dental chair laughing with a dentist in a navy scrub top, window light from the side, minimal oak and travertine interior, calm and warm",
    },
    "hero-video-poster": {
      kind: "video",
      aspect: "16:9",
      min: "1920×1080",
      usedOn: "Головна → Hero-відео (опційно, постер)",
      subject: "First frame of a silent 10–15 s loop: slow dolly through the clinic corridor into the treatment room",
      mood: MOOD_CLINIC,
      prompt:
        "Slow cinematic dolly shot first frame through a bright minimalist dental clinic corridor with oak panels and soft daylight leading into a treatment room",
    },

    "people-consultation": {
      kind: "people",
      aspect: "4:3",
      min: "2400×1800",
      usedOn: "Головна → Перший візит; Перший візит → hero",
      subject: "Doctor explaining a 3D treatment plan on a large screen to a couple, relaxed seating (not in the chair)",
      mood: MOOD_CLINIC,
      prompt:
        "A dentist sitting at a round table with a middle-aged couple explaining a 3D treatment plan on a large screen, relaxed consultation room with sofa-like chairs, coffee cups, natural daylight",
    },
    "people-calm-patient": {
      kind: "people",
      aspect: "4:5",
      min: "1800×2250",
      usedOn: "Головна → блок «Боїтеся?»; Лікування уві сні",
      subject: "Woman in her forties relaxed in the chair with headphones and a blanket; dim warm light; hand resting calmly",
      mood: "Low-key warm light, dark soft background (used in a dark section)",
      prompt:
        "A woman in her forties resting calmly in a dental chair with wireless headphones and a soft knit blanket, eyes closed, gentle smile, dim warm lighting, dark soft background, sense of safety",
    },
    "people-final-cta": {
      kind: "people",
      aspect: "16:9",
      min: "2880×1620",
      usedOn: "Головна → фінальний CTA (фон під склом)",
      subject: "Blurred-friendly background: reception with warm light, receptionist smiling, lots of calm space",
      mood: MOOD_CLINIC,
      prompt:
        "A warm premium dental clinic reception with a smiling receptionist behind a travertine desk, soft daylight, plants, calm and welcoming, generous negative space, slightly defocused",
    },
    "team-group": {
      kind: "people",
      aspect: "16:9",
      min: "2880×1620",
      usedOn: "Про клініку → Команда; Лікарі → hero",
      subject: "Whole team (9 doctors + assistants) standing naturally in the clinic lobby",
      mood: MOOD_CLINIC,
      prompt:
        "Group photo of a friendly dental clinic team of twelve people in coordinated navy, teal and white scrubs standing naturally in a bright minimalist lobby, relaxed smiles, editorial style",
    },

    "interior-reception": {
      kind: "interior",
      aspect: "4:3",
      min: "2400×1800",
      usedOn: "Про клініку → Інтер'єр",
      subject: "Reception desk and waiting lounge",
      mood: MOOD_CLINIC,
      prompt: "Premium dental clinic reception with a curved travertine desk, oak slat wall, designer lounge chairs, plants, soft daylight, no people",
    },
    "interior-cabinet": {
      kind: "interior",
      aspect: "4:3",
      min: "2400×1800",
      usedOn: "Про клініку → Інтер'єр; Технології",
      subject: "Treatment room: chair, microscope, big window",
      mood: MOOD_CLINIC,
      prompt: "Minimalist premium dental treatment room with a cream dental chair, white operating microscope, large window with greenery outside, warm oak cabinetry, no people",
    },
    "interior-lounge": {
      kind: "interior",
      aspect: "4:3",
      min: "2400×1800",
      usedOn: "Про клініку → Інтер'єр",
      subject: "Waiting lounge with coffee station",
      mood: MOOD_CLINIC,
      prompt: "Cozy waiting lounge in a premium clinic with boucle armchairs, coffee station, magazines, warm lamp and daylight, calm atmosphere, no people",
    },
    "interior-kids": {
      kind: "interior",
      aspect: "4:3",
      min: "2400×1800",
      usedOn: "Дитяча стоматологія; Про клініку",
      subject: "Kids' treatment room: tasteful, playful but not garish",
      mood: MOOD_CLINIC,
      prompt: "A tasteful kids' dental room with a pastel dental chair, a ceiling mural of soft clouds, wooden toys on a shelf, bright and calm, no people",
    },
    "interior-entrance": {
      kind: "interior",
      aspect: "4:3",
      min: "2400×1800",
      usedOn: "Контакти → «Як знайти вхід»",
      subject: "REAL PHOTO recommended: the actual building entrance with the NaDent sign",
      mood: "Daylight, straight-on, entrance clearly recognisable",
      prompt: "Modern clinic entrance with glass doors and a minimal illuminated sign, clean facade, daylight, street-level view",
    },
    "interior-sterilization": {
      kind: "interior",
      aspect: "4:3",
      min: "2400×1800",
      usedOn: "Головна → Стерильність; Про клініку → Стерилізація",
      subject: "Sterilization room with autoclave and sealed pouches",
      mood: MOOD_CLINIC,
      prompt: tech.sterilization[1],
    },
    "people-kids": {
      kind: "people",
      aspect: "4:5",
      min: "1800×2250",
      usedOn: "Головна → картка «Для дитини»",
      subject: "Child brushing teeth / laughing in the kids' room",
      mood: MOOD_CLINIC,
      prompt: "A laughing five-year-old boy holding an oversized toothbrush in a bright kids' dental room, playful, soft daylight",
    },
    "doctor-video-poster": {
      kind: "video",
      aspect: "16:9",
      min: "1920×1080",
      usedOn: "Сторінка лікаря → відео-знайомство (спільний постер, поки немає окремих)",
      subject: "Doctor sitting in the consultation room, looking at the camera, mid-sentence",
      mood: MOOD_CLINIC,
      prompt: "A dentist sitting in a bright consultation room speaking to the camera in a friendly way, interview framing, soft daylight, shallow depth of field",
    },
    "og-default": {
      kind: "og",
      aspect: "1200:630",
      min: "1200×630",
      usedOn: "Open Graph за замовчуванням (генерується автоматично, фото — опційний фон)",
      subject: "Calm clinic interior with space for the logo and a headline on the left",
      mood: MOOD_CLINIC,
      prompt: "Bright premium dental clinic interior, wide shot with generous empty space on the left for text, soft daylight, calm",
    },
  };

  for (const [id, s] of Object.entries(services)) {
    r[`service-${id}`] = {
      kind: "service",
      aspect: "4:3",
      min: "2400×1800",
      usedOn: `Послуга «${id}» → hero, картки послуг, bento на головній`,
      subject: `${s.subject}. Keep the subject centred with generous margins: the image is cropped to 4:5 and 16:10.`,
      mood: MOOD_CLINIC,
      prompt: s.prompt,
    };
  }

  for (const [id, [subject, prompt]] of Object.entries(tech)) {
    r[`tech-${id}`] = {
      kind: "equipment",
      aspect: "4:3",
      min: "2400×1800",
      usedOn: "Головна → Технології; /tekhnolohii; сторінки послуг",
      subject,
      mood: MOOD_CLINIC,
      prompt,
    };
  }

  for (const [slug, look] of Object.entries(doctors)) {
    r[`doctor-${slug}`] = {
      kind: "portrait",
      aspect: "4:5",
      min: "1600×2000",
      usedOn: `Лікарі; /likari/${slug}; сторінки послуг. REAL PHOTO strongly preferred.`,
      subject: `Waist-up portrait of ${look}, arms relaxed, looking at the camera, same backdrop and light for the whole team`,
      mood: MOOD_PORTRAIT,
      prompt: `Waist-up editorial portrait of ${look}, relaxed confident posture, genuine closed-mouth smile, looking at the camera`,
    };
  }

  for (const [id, title] of Object.entries(cases)) {
    for (const phase of ["before", "after"] as const) {
      r[`case-${id}-${phase}`] = {
        kind: "case",
        aspect: "4:3",
        min: "1600×1200",
        usedOn: `До / після → ${title}`,
        subject: `${phase === "before" ? "BEFORE" : "AFTER"} treatment intraoral / smile photo, identical framing, light and white balance for both shots`,
        prompt: "— (AI generation is not allowed: use real clinical photos with the patient's written consent)",
        realOnly: true,
      };
    }
  }

  for (const n of [1, 2, 3]) {
    r[`review-video-${n}`] = {
      kind: "video",
      aspect: "9:16",
      min: "1080×1920",
      usedOn: "Головна → Відгуки; /vidhuky (постер відео-відгуку)",
      subject: "Frame from a real patient's video testimonial",
      prompt: "— (real patients only, with written consent)",
      realOnly: true,
    };
  }

  for (const [id, prompt] of Object.entries(articles)) {
    r[`blog-${id}`] = {
      kind: "service",
      aspect: "16:10",
      min: "2400×1500",
      usedOn: `Блог → обкладинка статті «${id}»`,
      subject: prompt,
      mood: MOOD_CLINIC,
      prompt,
    };
  }

  for (const [id, prompt] of Object.entries({
    "hygiene-whitening": "Flat lay of a toothbrush, floss and a whitening shade guide on a sand-coloured surface, fresh and bright",
    "implant-consult": "Titanium implant model and a printed CT scan on a light oak desk in a consultation room",
    "family-checkup": "A parent and child brushing teeth together in front of a bathroom mirror, morning light, playful",
  })) {
    r[`offer-${id}`] = {
      kind: "service",
      aspect: "16:10",
      min: "2000×1250",
      usedOn: `Акції → «${id}»`,
      subject: prompt,
      mood: MOOD_CLINIC,
      prompt,
    };
  }

  return r;
}

export const imageRegistry = build() as Record<ImageId, ImageSpec>;

type ServiceImage = `service-${keyof typeof services}`;
type TechImage = `tech-${keyof typeof tech}`;
type DoctorImage = `doctor-${keyof typeof doctors}`;
type CaseImage = `case-${keyof typeof cases}-${"before" | "after"}`;
type ArticleImage = `blog-${keyof typeof articles}`;

export type ImageId =
  | "hero-desktop"
  | "hero-mobile"
  | "hero-video-poster"
  | "people-consultation"
  | "people-calm-patient"
  | "people-final-cta"
  | "people-kids"
  | "team-group"
  | "interior-reception"
  | "interior-cabinet"
  | "interior-lounge"
  | "interior-kids"
  | "interior-entrance"
  | "interior-sterilization"
  | "doctor-video-poster"
  | "og-default"
  | `review-video-${1 | 2 | 3}`
  | `offer-${"hygiene-whitening" | "implant-consult" | "family-checkup"}`
  | ServiceImage
  | TechImage
  | DoctorImage
  | CaseImage
  | ArticleImage;

export const SHARED_STYLE =
  "photorealistic, editorial healthcare photography, shot on a full-frame camera with a 50mm lens, soft natural daylight, premium minimalist Scandinavian clinic interior, warm neutral palette (ivory, sand, oak, travertine) with subtle deep-teal accents, real skin texture, natural healthy tooth shade (not bright white), authentic diverse Ukrainian people, calm and trustworthy mood, high dynamic range, no text";

export const SHARED_NEGATIVE =
  "overly white teeth, veneers look, plastic skin, cartoon, 3D render, clipart tooth, blue gloves close-up, blood, needles close-up, syringe, horror, dental tools in mouth close-up, distorted hands, extra fingers, text, watermark, logo, oversaturated, harsh flash, cold hospital lighting, stock-photo cheesiness";
